Para as questões 2-5 usaremos apenas os vinhos do tipo "branco".

Faça o download da base - esta é uma base real, apresentada no artigo:
P. Cortez, A. Cerdeira, F. Almeida, T. Matos and J. Reis. Modeling wine preferences by data mining from physicochemical properties. In Decision Support Systems, Elsevier, 47(4):547-553, 2009.

Ela possui uma variável denominada "quality", uma nota de 0 a 10 que denota a qualidade do vinho. Crie uma nova variável, chamada "opinion" que será uma variável categórica igual à 0, quando quality for menor e igual à 5. O valor será 1, caso contrário. Desconsidere a variável quality para o restante da análise.

Descreva as variáveis presentes na base. Quais são as variáveis? Quais são os tipos de variáveis (discreta, categórica, contínua)? Quais são as médias e desvios padrões?

Com a base escolhida:

Descreva as etapas necessárias para criar um modelo de classificação eficiente.

Treine um modelo de regressão logística usando um modelo de validação cruzada estratificada com k-folds (k=10) para realizar a classificação. Calcule para a base de teste:
i. a média e desvio da acurácia dos modelos obtidos;
ii. a média e desvio da precisão dos modelos obtidos;
iii. a média e desvio da recall dos modelos obtidos;
iv. a média e desvio do f1-score dos modelos obtidos.

Treine um modelo de árvores de decisão usando um modelo de validação cruzada estratificada com k-folds (k=10) para realizar a classificação. Calcule para a base de teste:
i. a média e desvio da acurácia dos modelos obtidos;
ii. a média e desvio da precisão dos modelos obtidos;
iii. a média e desvio da recall dos modelos obtidos;
iv. a média e desvio do f1-score dos modelos obtidos.

Treine um modelo de SVM usando um modelo de validação cruzada estratificada com k-folds (k=10) para realizar a classificação. Calcule para a base de teste:
i. a média e desvio da acurácia dos modelos obtidos;
ii. a média e desvio da precisão dos modelos obtidos;
iii. a média e desvio da recall dos modelos obtidos;
iv. a média e desvio do f1-score dos modelos obtidos.

Em relação à questão anterior, qual o modelo deveria ser escolhido para uma eventual operação. Responda essa questão mostrando a comparação de todos os modelos, usando um gráfico mostrando a curva ROC média para cada um dos gráficos e justifique.

Com a escolha do melhor modelo, use os dados de vinho tinto, presentes na base original e faça a inferência (não é para treinar novamente!!!) para saber quantos vinhos são bons ou ruins. Utilize o mesmo critério utilizado com os vinhos brancos, para comparar o desempenho do modelo. Ele funciona da mesma forma para essa nova base? Justifique.

Disponibilize os códigos usados para responder da questão 2-6 em uma conta github e indique o link para o repositório.

In [192]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from ydata_profiling import ProfileReport
from sklearn import datasets
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [193]:
data = "C:/Users/laiss/OneDrive/Arquivos/analista de dados/aprendizado supervisionado/winequalityN (1).csv"

In [194]:
df = pd.read_csv(data)

In [195]:
PF = ProfileReport(df) # colocando o dataframe dentro de uma variável no 
#profile report para ver o overview para entender os dados


In [196]:
#PF

In [197]:
df.head(10)

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0  white            7.0              0.27         0.36            20.7   
1  white            6.3              0.30         0.34             1.6   
2  white            8.1              0.28         0.40             6.9   
3  white            7.2              0.23         0.32             8.5   
4  white            7.2              0.23         0.32             8.5   
5  white            8.1              0.28         0.40             6.9   
6  white            6.2              0.32         0.16             7.0   
7  white            7.0              0.27         0.36            20.7   
8  white            6.3              0.30         0.34             1.6   
9  white            8.1              0.22         0.43             1.5   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.045                 45.0                 170.0   1.0010  3.00   
1      0.049                 14.0                 132.0   0.9940  3.30   
2      0.050                 30.0                  97.0   0.9951  3.26   
3      0.058                 47.0                 186.0   0.9956  3.19   
4      0.058                 47.0                 186.0   0.9956  3.19   
5      0.050                 30.0                  97.0   0.9951  3.26   
6      0.045                 30.0                 136.0   0.9949  3.18   
7      0.045                 45.0                 170.0   1.0010  3.00   
8      0.049                 14.0                 132.0   0.9940  3.30   
9      0.044                 28.0                 129.0   0.9938  3.22   

   sulphates  alcohol  quality  
0       0.45      8.8        6  
1       0.49      9.5        6  
2       0.44     10.1        6  
3       0.40      9.9        6  
4       0.40      9.9        6  
5       0.44     10.1        6  
6       0.47      9.6        6  
7       0.45      8.8        6  
8       0.49      9.5        6  
9       0.45     11.0        6

In [198]:
#no overview podemos observar dois tipos da única variável categorica white e red
# o exercício solicita que trabalhemos com os brancos. 

df_white = df.loc[df['type']=='white']

In [199]:
df_white.loc[:,'opnion']= df_white['quality'].apply(lambda x: 0 if x<=5 else 1) # criando a variável opnion
df_white = df_white.drop('quality', axis=1) # excluido a coluna quality
df_white.head()

C:\Users\laiss\AppData\Local\Temp\ipykernel_25100\1985496242.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_white.loc[:,'opnion']= df_white['quality'].apply(lambda x: 0 if x<=5 else 1) # criando a variável opnion


type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0  white            7.0              0.27         0.36            20.7   
1  white            6.3              0.30         0.34             1.6   
2  white            8.1              0.28         0.40             6.9   
3  white            7.2              0.23         0.32             8.5   
4  white            7.2              0.23         0.32             8.5   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.045                 45.0                 170.0   1.0010  3.00   
1      0.049                 14.0                 132.0   0.9940  3.30   
2      0.050                 30.0                  97.0   0.9951  3.26   
3      0.058                 47.0                 186.0   0.9956  3.19   
4      0.058                 47.0                 186.0   0.9956  3.19   

   sulphates  alcohol  opnion  
0       0.45      8.8       1  
1       0.49      9.5       1  
2       0.44     10.1       1  
3       0.40      9.9       1  
4       0.40      9.9       1

In [200]:
df_white_drop = df_white.drop_duplicates() # dropando duplicatas

In [201]:
df_white_drop = df_white.dropna(axis=0) # dropando valores nulos

In [202]:
PF = ProfileReport(df_white_drop) # visualizando o novo dataframe no overview


In [203]:
#PF

In [204]:
df_white_drop.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4870 entries, 0 to 4897
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   type                  4870 non-null   object 
 1   fixed acidity         4870 non-null   float64
 2   volatile acidity      4870 non-null   float64
 3   citric acid           4870 non-null   float64
 4   residual sugar        4870 non-null   float64
 5   chlorides             4870 non-null   float64
 6   free sulfur dioxide   4870 non-null   float64
 7   total sulfur dioxide  4870 non-null   float64
 8   density               4870 non-null   float64
 9   pH                    4870 non-null   float64
 10  sulphates             4870 non-null   float64
 11  alcohol               4870 non-null   float64
 12  opnion                4870 non-null   int64  
dtypes: float64(11), int64(1), object(1)
memory usage: 532.7+ KB


Variáveis categoricas (type) a opnion entrou no overview mesmo sendo categórica, mas no info entrou como contínua
Variáveis discretas (free sulfur dioxide,total sulfur dioxide)
Variáveis contínuas (fixed acidity, volatile acidity, citric acid, residual sugar, chlorides, density, pH, sulphates, alcohol)

In [205]:
df_white_drop.describe() #médias e desvios padrões das variáveis

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    4870.000000       4870.000000  4870.000000     4870.000000   
mean        6.855123          0.278071     0.334199        6.394343   
std         0.843444          0.100528     0.120915        5.070853   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.300000          0.210000     0.270000        1.700000   
50%         6.800000          0.260000     0.320000        5.200000   
75%         7.300000          0.320000     0.390000        9.900000   
max        14.200000          1.100000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  4870.000000          4870.000000           4870.000000  4870.000000   
mean      0.045771            35.317146            138.340144     0.994026   
std       0.021846            17.012967             42.490515     0.002993   
min       0.009000             2.000000              9.000000     0.987110   
25%       0.036000            23.000000            108.000000     0.991720   
50%       0.043000            34.000000            134.000000     0.993735   
75%       0.050000            46.000000            167.000000     0.996100   
max       0.346000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol       opnion  
count  4870.000000  4870.000000  4870.000000  4870.000000  
mean      3.188154     0.489700    10.516772     0.665298  
std       0.150902     0.114196     1.231251     0.471935  
min       2.720000     0.220000     8.000000     0.000000  
25%       3.090000     0.410000     9.500000     0.000000  
50%       3.180000     0.470000    10.400000     1.000000  
75%       3.280000     0.550000    11.400000     1.000000  
max       3.820000     1.080000    14.200000     1.000000

Para criação de um modelo:
-Entender bem o problema, coletar e separar os dados
-Definir as variáreis x features e a variável alvo y.
-Padronizar


In [206]:
df_white_drop.columns


Index(['type', 'fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'opnion'],
      dtype='object')

In [207]:
x = df_white_drop[['fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol']] # definindo variáveis inteiras e float
y = df_white_drop['opnion']

In [208]:
from sklearn.model_selection import train_test_split #incializando train e teste
from sklearn.preprocessing import StandardScaler # normalização
from sklearn.linear_model import LogisticRegression # modelo logistica regressa
from sklearn.model_selection import cross_val_score, StratifiedKFold # validação cruzada

In [209]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=10, stratify= y) 

In [210]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [211]:
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train) # modelo regressão logistica

In [212]:
yhat = LR.predict(X_test)

In [213]:
#avaliação das metricas no test por validação cruzada
accuracy_scores = cross_val_score(LR, X_test, y_test, cv=10, scoring='accuracy')
precision_scores = cross_val_score(LR, X_test, y_test, cv=10, scoring='precision')
recall_scores = cross_val_score(LR, X_test, y_test, cv=10, scoring='recall')
f1_score = cross_val_score(LR, X_test, y_test, cv=10, scoring='f1')

In [214]:
accuracy_scores

array([0.72789116, 0.7739726 , 0.78082192, 0.81506849, 0.76027397,
       0.73287671, 0.7260274 , 0.76027397, 0.75342466, 0.76027397])

In [215]:
accuracy_scores.mean()

0.7590904855092722

In [216]:
accuracy_scores.std()

0.025724115681892763

In [217]:
precision_scores

array([0.76363636, 0.7826087 , 0.78761062, 0.80701754, 0.76724138,
       0.74166667, 0.76146789, 0.78703704, 0.76521739, 0.75409836])

In [218]:
precision_scores.mean()

0.7717601947499604

In [219]:
precision_scores.std()

0.01816068685099947

In [220]:
recall_scores

array([0.85714286, 0.91836735, 0.91752577, 0.94845361, 0.91752577,
       0.91752577, 0.8556701 , 0.87628866, 0.90721649, 0.94845361])

In [221]:
recall_scores.mean()

0.9064169997896065

In [222]:
recall_scores.std()

0.03155744438196656

In [223]:
f1_score

array([0.80769231, 0.84507042, 0.84761905, 0.87203791, 0.83568075,
       0.8202765 , 0.80582524, 0.82926829, 0.83018868, 0.84018265])

In [224]:
f1_score.mean()

0.8333841804456554

In [225]:
f1_score.std()

0.018717197316252564

In [226]:
# avaliação das metricas individuais na predição

print("Accuracy Test:",metrics.accuracy_score(y_test, yhat))
print("Precision Test:",metrics.precision_score(y_test,yhat))
print("Recall Test:",metrics.recall_score(y_test,yhat))
print("f1-score Test:",metrics.f1_score(y_test,yhat))

Accuracy Test: 0.7501711156741958
Precision Test: 0.7802400738688827
Recall Test: 0.8693415637860082
f1-score Test: 0.8223844282238443


In [227]:
from sklearn.tree import DecisionTreeClassifier, plot_tree # modelo árvore de decisão

In [228]:
dTree = DecisionTreeClassifier(criterion="entropy", max_depth = 5) # classificação tamanho da arvora

In [229]:
dTree = dTree.fit(X_train,y_train)

In [230]:
yhat = dTree.predict(X_test)
yhat

array([1, 0, 1, ..., 1, 1, 1], dtype=int64)

In [231]:
accuracy_scores = cross_val_score(dTree, X_test, y_test, cv=10, scoring='accuracy')
precision_scores = cross_val_score(dTree, X_test, y_test, cv=10, scoring='precision')
recall_scores = cross_val_score(dTree,  X_test, y_test, cv=10, scoring='recall')
f1_score = cross_val_score(dTree,  X_test, y_test, cv=10, scoring='f1')

In [232]:
accuracy_scores

array([0.7414966 , 0.73287671, 0.7260274 , 0.74657534, 0.71917808,
       0.76027397, 0.75342466, 0.73287671, 0.7739726 , 0.74657534])

In [233]:
accuracy_scores.std()

0.015664076313735814

In [234]:
accuracy_scores.mean()

0.7433277420557265

In [235]:
precision_scores

array([0.80412371, 0.73387097, 0.77142857, 0.75862069, 0.79787234,
       0.81      , 0.76068376, 0.77358491, 0.80188679, 0.76785714])

In [236]:
precision_scores.mean()

0.7779928882245529

In [237]:
precision_scores.std()

0.023367225209970942

In [238]:
recall_scores 

array([0.79591837, 0.92857143, 0.83505155, 0.90721649, 0.77319588,
       0.83505155, 0.92783505, 0.84536082, 0.87628866, 0.88659794])

In [239]:
recall_scores.mean()


0.8611087734062698

In [240]:
recall_scores.std()


0.05059058909593931

In [241]:
f1_score

array([0.8       , 0.82352941, 0.8019802 , 0.82629108, 0.78534031,
       0.82233503, 0.84507042, 0.8097561 , 0.83743842, 0.82296651])

In [242]:
f1_score.mean()

0.8174707480032092

In [243]:
f1_score.std()

0.017221745307696247

In [244]:
print("Accuracy Test:",metrics.accuracy_score(y_test, yhat))
print("Precision Test:",metrics.precision_score(y_test,yhat))
print("Recall Test:",metrics.recall_score(y_test,yhat))
print("f1-score Test:",metrics.f1_score(y_test,yhat))

Accuracy Test: 0.7351129363449692
Precision Test: 0.7815206929740135
Recall Test: 0.8353909465020576
f1-score Test: 0.8075584286424664


In [245]:
from sklearn import svm
clf = svm.SVC(kernel='rbf')
clf.fit(X_train, y_train)

SVC()

In [246]:
yhat = clf.predict(X_test)
yhat

array([1, 0, 1, ..., 1, 1, 1], dtype=int64)

In [247]:
accuracy_scores = cross_val_score(clf, X_test, y_test, cv=10, scoring='accuracy')
precision_scores = cross_val_score(clf, X_test, y_test, cv=10, scoring='precision')
recall_scores = cross_val_score(clf,  X_test, y_test, cv=10, scoring='recall')
f1_score = cross_val_score(clf,  X_test, y_test, cv=10, scoring='f1')

In [248]:
accuracy_scores

array([0.7414966 , 0.82191781, 0.75342466, 0.79452055, 0.80821918,
       0.74657534, 0.7739726 , 0.80821918, 0.80821918, 0.73972603])

In [249]:
accuracy_scores.mean()

0.7796291119187402

In [250]:
accuracy_scores.std()

0.030528397068087677

In [251]:
precision_scores

array([0.77777778, 0.82727273, 0.77477477, 0.79130435, 0.80530973,
       0.78301887, 0.82653061, 0.81651376, 0.8       , 0.7706422 ])

In [252]:
precision_scores.mean()

0.797314480563682

In [253]:
precision_scores.std()

0.020080949094924548

In [254]:
recall_scores

array([0.85714286, 0.92857143, 0.88659794, 0.93814433, 0.93814433,
       0.8556701 , 0.83505155, 0.91752577, 0.94845361, 0.86597938])

In [255]:
recall_scores.mean()

0.8971281296023564

In [256]:
recall_scores.std()

0.03956757340099116

In [257]:
f1_score

array([0.81553398, 0.875     , 0.82692308, 0.85849057, 0.86666667,
       0.81773399, 0.83076923, 0.86407767, 0.86792453, 0.81553398])

In [258]:
f1_score.mean()

0.8438653689914342

In [259]:
f1_score.std()

0.023317965740405344

In [260]:
print("Accuracy Test:",metrics.accuracy_score(y_test, yhat))
print("Precision Test:",metrics.precision_score(y_test,yhat))
print("Recall Test:",metrics.recall_score(y_test,yhat))
print("f1-score Test:",metrics.f1_score(y_test,yhat))

Accuracy Test: 0.7939767282683093
Precision Test: 0.8174077578051088
Recall Test: 0.8888888888888888
f1-score Test: 0.8516510596352883


In [261]:
from sklearn.metrics import confusion_matrix, roc_auc_score, roc_curve, RocCurveDisplay
import matplotlib.pyplot as plt
from sklearn.metrics import RocCurveDisplay


In [262]:
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt

In [263]:
# Criando um objeto de figura e eixos para as curvas
fig, ax = plt.subplots()

# Plotando a curva ROC para cada modelo
roc_display_LR = RocCurveDisplay.from_estimator(LR, X_test, y_test, ax=ax, name='Logistic Regression')
roc_display_dTree = RocCurveDisplay.from_estimator(dTree, X_test, y_test, ax=ax, name='Decision Tree')
roc_display_clf = RocCurveDisplay.from_estimator(clf, X_test, y_test, ax=ax, name='SVM')

# Ajusta o layout para as curvas
plt.tight_layout()

# Exibi o gráfico, porem abre uma janela, meu vs code não tava conseguindo plotar, dai immportei matplotlib.use('TkAgg')
#na qual, gera um arquivo das tres curvas quando roda.
plt.show()



KeyboardInterrupt: 

Diante da curva ROC podemos dizer que o melhor modelo é o de SVM, pois é a curva que está mais próxima do canto superiror e 
tem como AUC = 0,84 ou seja, o mais perto de 1

In [264]:
# testando na base dos vinhos vermelhos

In [265]:
df_red = df.loc[df['type']=='red']

In [266]:
df_red.loc[:,'opnion']= df_red['quality'].apply(lambda x: 0 if x<=5 else 1) # criando a variável opnion
df_red= df_red.drop('quality', axis=1) # excluido a coluna quality
df_red.head()

C:\Users\laiss\AppData\Local\Temp\ipykernel_25100\1308888139.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_red.loc[:,'opnion']= df_red['quality'].apply(lambda x: 0 if x<=5 else 1) # criando a variável opnion


type  fixed acidity  volatile acidity  citric acid  residual sugar  \
4898  red            7.4              0.70         0.00             1.9   
4899  red            7.8              0.88         0.00             2.6   
4900  red            7.8              0.76         0.04             2.3   
4901  red           11.2              0.28         0.56             1.9   
4902  red            7.4              0.70         0.00             1.9   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
4898      0.076                 11.0                  34.0   0.9978  3.51   
4899      0.098                 25.0                  67.0   0.9968  3.20   
4900      0.092                 15.0                  54.0   0.9970  3.26   
4901      0.075                 17.0                  60.0   0.9980  3.16   
4902      0.076                 11.0                  34.0   0.9978  3.51   

      sulphates  alcohol  opnion  
4898       0.56      9.4       0  
4899       0.68      9.8       0  
4900       0.65      9.8       0  
4901       0.58      9.8       1  
4902       0.56      9.4       0

In [267]:
df_red_drop = df_red.drop_duplicates()

In [268]:
df_red_drop = df_red.dropna(axis=0)

In [269]:
df_red_drop.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1593 entries, 4898 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   type                  1593 non-null   object 
 1   fixed acidity         1593 non-null   float64
 2   volatile acidity      1593 non-null   float64
 3   citric acid           1593 non-null   float64
 4   residual sugar        1593 non-null   float64
 5   chlorides             1593 non-null   float64
 6   free sulfur dioxide   1593 non-null   float64
 7   total sulfur dioxide  1593 non-null   float64
 8   density               1593 non-null   float64
 9   pH                    1593 non-null   float64
 10  sulphates             1593 non-null   float64
 11  alcohol               1593 non-null   float64
 12  opnion                1593 non-null   int64  
dtypes: float64(11), int64(1), object(1)
memory usage: 174.2+ KB


In [270]:
x = df_red_drop[['fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol']] # definindo variáveis inteiras e float
y = df_red_drop['opnion']

In [271]:
from sklearn import svm
clf = svm.SVC(kernel='rbf')
clf.fit(X_test, y_test)

SVC()

In [272]:
yhat = clf.predict(X_test) # o modelo funciona para vinhos vermelhos classificando 
yhat

array([1, 0, 1, ..., 1, 1, 1], dtype=int64)

In [273]:

print("Accuracy Test:",metrics.accuracy_score(y_test, yhat))
print("Precision Test:",metrics.precision_score(y_test,yhat))
print("Recall Test:",metrics.recall_score(y_test,yhat))
print("f1-score Test:",metrics.f1_score(y_test,yhat))

Accuracy Test: 0.8268309377138946
Precision Test: 0.8319482917820868
Recall Test: 0.926954732510288
f1-score Test: 0.8768856447688564


As metricas apontam que o modelo fica ainda melhor para vinhos vermelhos